version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=journal_db
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./backend/src:/app/src
      - ./backend/node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=journal_db
      - MYSQL_USER=your_db_user
      - MYSQL_PASSWORD=your_db_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
